# This is a sample of a credentials file, used when creating credentials.yml.enc
# DO NOT ADD ACTUAL KEYS TO THIS FILE

# aws:
#   access_key_id: 123
#   secret_access_key: 345

recaptcha:
  site_key: # Key
  secret_key: # Key

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: # Generate a random, 128-character hex string.
